var ticTacToeEngine = (function() {

  var b = atob("AAAAAAAAAAAAFB4XCAAdABMADA4EHhgIBAgHFBoQAAARBhkbCAAeFB8GAB8AGQAADAAXERAAGgAbAA8PBAsLFQsOGgASHxAJBQ8AAAQfHwAAAA0AAB0ABxMPABsEDwAAABcYDBAAAAUcHQAAABsTAAAAHgoaAA4fACMAABEdAAgVACMADgAXAAAAGwAAABAAAAwgAAYjABYACAAAHxsbAAAACCMAChoMABoAABwIAAAADAAACBMAABQAGRsKEwgLEwANACMcEAAAABsaFgQdFxgfABYeAAAaCxsRAAAjBxAMCB8OCgAjAAwMABQADgAUFwAAAAAACwsfFAsYABgAIgAACAATAAAjGSMAAB8XHgQABAoTDQcaDhAbBh4JABMAAAAfDwsLFQAACgAACyIjIxQAAB0AGwsMAAALCwAAHwAAAAALDwAAAAAQIgkAFwgAAAATAAAAAAAADwAPAAAPFhwABwAAACMaAAAAAAAAFggYBgAAEhcEEgAiEQAEDwcABgAWIAAKABcEAAUADCMAFA4dHAAABwAAACAdIxIAEAAKCAAAAAAAAA8AIwAAAAAAABEEAAAEIyMADAAXCxAAGyMUAAAAFgAABwAAAAAHEBAAAAAAACAYAAAQAAwAAB8YIRAABRIAFgAAHhUXIwAAACMAAAAjGwAAFwAEAAAAAAUABggABxcFAB8GIiMcACAGABUAEiMACAAfHBUXHBwjCAAAAAAACxgNABcAAAoACCIAAA8PAAAOACIjACMABx8XGxYZAAAADCIXBAAPAAsAAAAAFw8fAAYKACAaAAAgEBgAABAAAAAADw4AFhASCQAjAAAACwAAAAALDxsAHwAhAAAWDRYADRcABAsAAAAAACASABwHABwYDAAKBQ8AAAAfAAAADBMYGwAKABkRABoAAAAAIwAcAAAAAAAEAAAAAAAfAAAAAAAEAAAAAAAAABcAABYAAAAAAA0ADAAAAAAAAAAACAAAAAAMAAAWBwsAACEAHAAAAAAAAAAACgAAABQACgAAAAAACCAAHxcAEgAdBwAAAAAAAAcAHBAAAAAACgAAABMiAAAAAAAAAAAAEAAAAAALAAAAAAAQAA0AAAAWAAAAFgAPAAAAAAAACAAAAAAAAAAAAAAAGwAAAAAXABcAAAAAAAAAAAAEAAAAAAAAAAwAFwAAAAAAAAAiEhAAIwAAAAAAAAAAAAAAAAAHAAAAAAAAAAAACwAAHQAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAICgAAAAAAAAAGAAAADwAOGwAAAAAfAAAAAA8AAAAPAAAAAAwAAAAAAAAAAAAAAAAAAAAABgAAAAAAEwAAGhYAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPFgAAAAAAAAAAEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAsAAAAAAAAAAAAAACMAAAAAHwAAAAAAAAAAAAAAAAAAAAAAAA8AEgAAABwAAAAXAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADw==");
  var board = 0;
  var humanHand;
  var botHand;
  var status;
  var hash = new Int16Array([ 4,220,90,137,358,230,54,1,6,476,26,39,278,17,525,8,2,87,94,159,0,85,638,230,46,25,33,167,6,234,219,302,17,261,38,19,267,435,258,514,295,202,635,126,514,487,363,58]);  
               
  function initBoard(hHand) {
      board = 0;
      humanHand = hHand;
      botHand = humanHand ^ 3; 
  } 
  
  function makeMove(hand, cell) {
      board += hand * Math.pow(3,cell);
  }
  
  function getIndexOfBoard() {
      return hash[(board & 31) + 16]
           + hash[((board >> 5) & 31) + 7]
           + hash[((board >> 10) & 31)];
  }
  
  function getBotMove() {
      var idx = getIndexOfBoard(board);
      var result = b.charCodeAt(idx);
      var cell = result >> 2;
      status = result & 3;
      makeMove(botHand, cell);
      return cell; 
  }
  
  function setHumanMove(cell) {
      makeMove(humanHand, cell);
      console.log(board);
  }
  
  function getStatus() {
      return status;
  }  
  
  return {
      initBoard: initBoard,
      getBotMove: getBotMove,
      setHumanMove: setHumanMove,
      getStatus: getStatus
  };
    
})();